services:
  postgres:
    image: postgres:9.5
    env_file:
      # Environment variables for postgres user and password must
      # be set in the .env file!
      - .env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      SERVICE_MANAGER: 'fsm-postgres'
    volumes:
      - 'discuss-db:/var/lib/postgresql/data/'


volumes:
  discuss-db: